spring:
  application:
    name: usda-fdc-mcp-server
  threading:
    virtual:
      enabled: true
  main:
    web-application-type: NONE
    banner-mode: off
  ai:
    mcp:
      server:
        stdio: true
        name: usda-fdc-mcp-server
        type: SYNC